apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: db:5433
    user: root
    secureJsonData:
      password: root
    jsonData:
      database: test
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    uid: postgres-ds
